{% set name = "oneclient" %}
{% set version = "<<PKG_VERSION>>" %}
{% set folly_version = "2017.10.02.00" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace('-', '.') }}

source:
  url: "<<PKG_SOURCE>>"

build:
  string: py{{ py }}
  binary_relocation: true
  script_env:
    - PKG_VERSION

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - conda-forge::autoconf
    - conda-forge::autoconf-archive
    - conda-forge::automake
    - conda-forge::aws-c-common
    - conda-forge::aws-checksums
    - conda-forge::aws-c-event-stream
    - conda-forge::aws-sdk-cpp
    - conda-forge::boost >=1.77.0
    - conda-forge::cmake
    - conda-forge::double-conversion
    - conda-forge::fmt =7.1.*
    - conda-forge::poco =1.11.*
    - conda-forge::gflags
    - conda-forge::git
    - conda-forge::glog
    - conda-forge::gperf
    - onedata::libacl
    - onedata::libattr
    - conda-forge::libevent
    - onedata::libiberty
    - conda-forge::libsodium
    - conda-forge::libtool
    - conda-forge::libfuse =2.9.*
    - conda-forge::libuuid
    - conda-forge::make
    - conda-forge::nss
    - conda-forge::nspr
    - conda-forge::openssl =1.1.*
    - conda-forge::pcre
    - conda-forge::pkg-config >=0.29
    - conda-forge::protobuf =3.17.*
    - conda-forge::pthread-stubs
    - python {{ python }}
    - conda-forge::spdlog =1.8.*
    - conda-forge::tbb =2018.0.5
    - conda-forge::tbb-devel =2018.0.5
    - onedata::ceph-client =14.2.2
    - onedata::swift-sdk-cpp =1.0.1
    - onedata::folly ={{ folly_version }}
    - onedata::wangle ={{ folly_version }}
    - onedata::proxygen ={{ folly_version }}
  run:
    - conda-forge::aws-c-common
    - conda-forge::aws-c-event-stream
    - conda-forge::aws-checksums
    - conda-forge::aws-sdk-cpp
    - conda-forge::boost >=1.77.0
    - conda-forge::double-conversion
    - conda-forge::gflags
    - conda-forge::glog =0.4.0
    - conda-forge::fmt =7.1.*
    - conda-forge::libfuse =2.9.*
    - conda-forge::jemalloc
    - conda-forge::libevent
    - conda-forge::libfuse
    - conda-forge::libsodium
    - conda-forge::libunwind
    - conda-forge::libuuid
    - conda-forge::nspr
    - conda-forge::nss
    - conda-forge::openssl =1.1.*
    - conda-forge::pcre
    - conda-forge::poco =1.11.*
    - conda-forge::protobuf =3.17.*
    - conda-forge::spdlog =1.8.*
    - conda-forge::tbb =2018.0.5
    - conda-forge::zlib
    - onedata::ceph-client =14.2.2
    - onedata::folly ={{ folly_version }}
    - onedata::proxygen ={{ folly_version }}
test:
  commands:
    - test -f $PREFIX/bin/oneclient
    - $PREFIX/bin/oneclient --version

about:
  home: https://onedata.org
  license: MIT
  summary: Oneclient is the Onedata command line interface for mounting distributed virtual filesystem on local machines.

extra:
  recipe-maintainers:
    - bkryza
