{% set name = "oneclient" %}
{% set version = "<<PKG_VERSION>>" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace('-', '.') }}

source:
  url: "<<PKG_SOURCE>>"

build:
  binary_relocation: true
  script_env:
    - PKG_VERSION

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - conda-forge::aws-c-common
    - conda-forge::aws-checksums
    - conda-forge::aws-c-event-stream
    - conda-forge::aws-sdk-cpp
    - conda-forge::backports.lzma
    - conda-forge::boost
    - onedata::ceph-client =14.2.4
    - conda-forge::cmake
    - conda-forge::double-conversion
    - conda-forge::fmt =7.1.3
    - conda-forge::poco
    - onedata::swift-sdk-cpp
    - conda-forge::gflags
    - conda-forge::git
    - conda-forge::glog =0.4.0
    - onedata::glusterfs-client
    - conda-forge::gperf
    - conda-forge::jemalloc
    - onedata::libacl
    - onedata::libattr
    - conda-forge::libevent
    - conda-forge::libsodium
    - conda-forge::libtool
    - conda-forge::libfuse
    - conda-forge::libuuid
    - conda-forge::make
    - conda-forge::nss
    - conda-forge::nspr
    - conda-forge::openssl
    - conda-forge::pcre
    - conda-forge::pkg-config
    - conda-forge::protobuf =3.17.2
    - conda-forge::pthread-stubs
    - conda-forge::python
    - conda-forge::spdlog
    - conda-forge::tbb =2018.0.5
    - conda-forge::tbb-devel =2018.0.5
  run:
    - conda-forge::boost
    - onedata::ceph-client =14.2.4
    - conda-forge::gflags
    - conda-forge::glog =0.4.0
    - onedata::glusterfs-client
    - conda-forge::libfuse
    - conda-forge::libsodium
    - conda-forge::nss
    - conda-forge::nspr
    - conda-forge::openssl
    - conda-forge::pcre
    - conda-forge::poco
    - conda-forge::protobuf =3.17.2
    - conda-forge::tbb =2018.0.5
    - conda-forge::zlib

test:
  commands:
    - test -f $PREFIX/bin/oneclient
    - $PREFIX/bin/oneclient --version

about:
  home: https://onedata.org
  license: MIT
  summary: Oneclient is the Onedata command line interface for mounting distributed virtual filesystem on local machines.

extra:
  recipe-maintainers:
    - bkryza
